# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_pic',
            field=models.FileField(default=datetime.datetime(2016, 4, 13, 7, 35, 14, 490903, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.IntegerField(),
        ),
    ]
